### ISSUE TITLE
Excuse me, could  You share the pretrained model “mobilenetV2”

### ISSUE THREAD

**Issue by EEEEEREN** [adrift00/Siamtracker#2]
I also want to train SiamRPN ++ based on the MobileNetV2, but the”pysot” only release the resnet 50. I am bother you to share your pretrain model.
 Thank you, by the way, did u still keep 3 RPNs on mobileNet?
I really want to know how did you modify the backbone 

您好，我也想训练基于mobilenet的siamrpn++，但是pysot上只释放了resnet50的预训练模型。请问您可以分享一下你的pretrain_models那个文件夹下的mobilenet的网络吗。
顺便问下，你也是在mobilenet上保留了3个rpn块吗。 
我很想知道您是怎么改成mobilenet的

**Comment by adrift00** [comment]
I'm so sorry that I haven't reproduce the performance reported in the SiamRPN++ paper, so my pretrained model may not work for you. My mobilenetv2 based model only achieves 0.3 EAO in VOT2018, but the official report is  0.39.  
I still use 3 RPNs on mobilenetv2, just like the code in pysot.

**Comment by EEEEEREN** [comment]
its fine , its ok, all i want to do is train this tracker with Mobilenet, there is no pretrained model in github, just .pth. due to i am a rookie in python and siamese tracker , so i just want to try it
没事的，性能什么的没关系，我就是想基于mobilenet上训练一下Siamrpn++，😂 因为github上都是.pth文件，只能拿来做测试，没有.model文件，因为我不是很擅长python，所以就是想自己在mobilenet上训练完再测试，不用关心性能的😂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adrift00/Siamtracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)





 
I'm so sorry that I haven't reproduce the performance reported in the SiamRPN++ paper, so my pretrained model may not work for you. My mobilenetv2 based model only achieves 0.3 EAO in VOT2018, but the official report is  0.39.
 I still use 3 RPNs on mobilenetv2, just like the code in pysot.

**Comment by EEEEEREN** [comment]
so if u could share the pretrained model, it ll be very grateful to you 🙏

**Comment by adrift00** [comment]
Ok, could you leave your email address or other contact information? I will send you the pretrained model file. 
But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code.
By the way, I train the pretrained model using my another repo [imagenet_pretrain](https://github.com/adrift00/imagenet_pretrain) , I think you can try to train it by yourself.

**Comment by EEEEEREN** [comment]
> Ok, could you leave your email address or other contact information? I will send you the pretrained model file.
> But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code.
> By the way, I train the pretrained model using my another repo [imagenet_pretrain](https://github.com/adrift00/imagenet_pretrain) , I think you can try to train it by yourself.

oh, sorry i have not got your reply utill now ,   My Email address is 451304917@qq.com   thanks a lot!!!! 🙏

**Comment by EEEEEREN** [comment]
> Ok, could you leave your email address or other contact information? I will send you the pretrained model file.
> But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code.
> By the way, I train the pretrained model using my another repo [imagenet_pretrain](https://github.com/adrift00/imagenet_pretrain) , I think you can try to train it by yourself.

i've got the files, thanks a lot.     but in TRAIN.md from <pysot>,  we need download pretrained backbones as follow 
![QQ截图20210318164653](https://user-images.githubusercontent.com/67900018/111597948-ab99d200-8809-11eb-994e-bb08b533836d.png)
in this Google Driver link , there is a pretrained backbone-----resnet50.model
![QQ截图20210318165052](https://user-images.githubusercontent.com/67900018/111598358-1c40ee80-880a-11eb-954e-97d4152fe9b7.png)
then , put it into <pretrain_models> , but pysot did not provide backbone mobilenetv2.model  only resnet50.model
did u have it ?

我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗

**Comment by adrift00** [comment]
I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)





  
Ok, could you leave your email address or other contact information? I will send you the pretrained model file.
 But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code.
 By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself.
  
i've got the files, thanks a lot.     but in TRAIN.md from ,  we need download pretrained backbones as follow
 
 in this Google Driver link , there is a pretrained backbone-----resnet50.model
 
 then , put it into <pretrain_models&gt; , but pysot did not provide backbone mobilenetv2.model  only resnet50.model
 did u have it ?
 
我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗

**Comment by EEEEEREN** [comment]
did u have your own mobilenetV2.model?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "adrift00/Siamtracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)





 I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年3月18日(星期四) 下午4:58 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2) 
 
 
 
 
 
    
 Ok, could you leave your email address or other contact information? I will send you the pretrained model file. 
  But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code. 
  By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself. 
    
 i've got the files, thanks a lot.     but in TRAIN.md from ,  we need download pretrained backbones as follow 
   
  in this Google Driver link , there is a pretrained backbone-----resnet50.model 
   
  then , put it into <pretrain_models&amp;gt; , but pysot did not provide backbone mobilenetv2.model  only resnet50.model 
  did u have it ? 
   
 我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗

**Comment by adrift00** [comment]
The file “mobilenetv2_1.4.pth" is my own pretrained file. You don't need to care about the file name, thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)





 did u have your own mobilenetV2.model? 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "adrift00/Siamtracker"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年3月18日(星期四) 下午5:06 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2) 
 
 
 
 
 
  I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年3月18日(星期四) 下午4:58  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)  
   
   
   
   
   
      
  Ok, could you leave your email address or other contact information? I will send you the pretrained model file.  
   But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code.  
   By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself.  
      
  i've got the files, thanks a lot.     but in TRAIN.md from ,  we need download pretrained backbones as follow  
     
   in this Google Driver link , there is a pretrained backbone-----resnet50.model  
     
   then , put it into <pretrain_models&amp;amp;gt; , but pysot did not provide backbone mobilenetv2.model  only resnet50.model  
   did u have it ?  
     
  我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗

**Comment by EEEEEREN** [comment]
> The file “mobilenetv2_1.4.pth" is my own pretrained file. You don't need to care about the file name, thank you.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月18日(星期四) 下午5:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) did u have your own mobilenetV2.model?
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "adrift00/Siamtracker" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2021年3月18日(星期四) 下午5:06 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&amp;amp;nbsp;
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: ***@***.***&amp;amp;gt;; 发送时间: 2021年3月18日(星期四) 下午4:58 收件人: ***@***.***&amp;amp;gt;; 抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) Ok, could you leave your email address or other contact information? I will send you the pretrained model file. But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code. By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself. i've got the files, thanks a lot. but in TRAIN.md from , we need download pretrained backbones as follow in this Google Driver link , there is a pretrained backbone-----resnet50.model then , put it into <pretrain_models&amp;amp;gt; , but pysot did not provide backbone mobilenetv2.model only resnet50.model did u have it ? 我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

thank u very much , i am a real rookie in this area!!!!  appreciate！！

**Comment by EEEEEREN** [comment]
> The file “mobilenetv2_1.4.pth" is my own pretrained file. You don't need to care about the file name, thank you.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月18日(星期四) 下午5:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) did u have your own mobilenetV2.model?
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "adrift00/Siamtracker" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2021年3月18日(星期四) 下午5:06 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&amp;amp;nbsp;
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: ***@***.***&amp;amp;gt;; 发送时间: 2021年3月18日(星期四) 下午4:58 收件人: ***@***.***&amp;amp;gt;; 抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) Ok, could you leave your email address or other contact information? I will send you the pretrained model file. But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code. By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself. i've got the files, thanks a lot. but in TRAIN.md from , we need download pretrained backbones as follow in this Google Driver link , there is a pretrained backbone-----resnet50.model then , put it into <pretrain_models&amp;amp;gt; , but pysot did not provide backbone mobilenetv2.model only resnet50.model did u have it ? 我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

excuse me， i got some problems when i try to use your mobilenetnetv2_1.4.pth in pysot
here is the problem 

![QQ截图20210323111750](https://user-images.githubusercontent.com/67900018/112087932-dac59000-8bc9-11eb-8bf0-6d2fe734cd01.png)

this is my config.yaml 
![1](https://user-images.githubusercontent.com/67900018/112088049-0ba5c500-8bca-11eb-977f-5c14919054d9.png)
![2](https://user-images.githubusercontent.com/67900018/112088054-0d6f8880-8bca-11eb-986b-42f184840acc.png)
maybe i need a  checkpoint_e34 ?  or maybe my config.yaml has something  wrong ?

**Comment by adrift00** [comment]
You can debug model_load.py to see what the specific problem is. May be you can modify the load_pretrain function like this







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [adrift00/Siamtracker] Excuse me, could  You share the pretrained model “mobilenetV2” (#2)





  
The file “mobilenetv2_1.4.pth" is my own pretrained file. You don't need to care about the file name, thank you.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月18日(星期四) 下午5:09 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) did u have your own mobilenetV2.model?
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "adrift00/Siamtracker" @.&amp;gt;; 发送时间:&amp;nbsp;2021年3月18日(星期四) 下午5:06 @.&amp;gt;; @.@.&amp;gt;; 主题:&amp;nbsp;Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) I have sent you the mobilenetv2.pth, it is the model file I pretrained on imagenet. Maybe you can use it for training. If you want to get the mobilenetv2.model provided by pysot author, I'm sorry I don't have it, because the author of pysot doesn't provide it for us.&amp;amp;nbsp;
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: @.&amp;amp;gt;; 发送时间: 2021年3月18日(星期四) 下午4:58 收件人: @.&amp;amp;gt;; 抄送: @.&amp;amp;gt;; @.&amp;amp;gt;; 主题: Re: [adrift00/Siamtracker] Excuse me, could You share the pretrained model “mobilenetV2” (#2) Ok, could you leave your email address or other contact information? I will send you the pretrained model file. But because I have modified some code, maybe it can't be apply to pysot directly, you can modify pysot by referring to my code. By the way, I train the pretrained model using my another repo imagenet_pretrain , I think you can try to train it by yourself. i've got the files, thanks a lot. but in TRAIN.md from , we need download pretrained backbones as follow in this Google Driver link , there is a pretrained backbone-----resnet50.model then , put it into <pretrain_models&amp;amp;gt; , but pysot did not provide backbone mobilenetv2.model only resnet50.model did u have it ? 我收到了您的文件，很感谢。但是在pysot中，如果我想要训练原始代码的话，需要从pysot提供的一个谷歌网盘中下载resnet50.model的预训练骨干网络文件. 但是pysot只提供了resnet50.model 没有MobilenetV2.model的骨干网络，您有这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
excuse me， i got some problems when i try to use your mobilenetnetv2_1.4.pth in pysot
 here is the problem
 

 
this is my config.yaml
 
 
 maybe i need a  checkpoint_e34 ?  or maybe my config.yaml has something  wrong ?
